version: "3.9"
services:
    postgresdockerautohaus:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: "${pguser}"
            POSTGRES_PASSWORD: "${pgpassword}"
        ports:
            - 5446:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data:
        driver: local
networks:
    default:
        external:
            name: "${DOCKER_NETWORK}"
