version: "3.9"
services:
    autohaus:
        build:
            context: .
            dockerfile: Dockerfile.prod
            network: "${DOCKER_NETWORK}" 
        ports:
            - 3005:3000
        volumes:
            - .swc:/app/swc
            - ./components:/app/components
            - ./lib:/app/lib
            - ./pages:/app/pages
            - ./prisma:/app/prisma
            - ./strapiAPI:/app/strapiAPI
            - ./styles:/app/styles
            - ./.env:/app/.env 
        command: "npm run server"
        deploy:
            resources:
                limits:
                    cpus: '1.25'
                    memory: 2000m
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
networks:
    default:
        external: true
        name: "${DOCKER_NETWORK}"