version: "3.9"
services:
    autohaus:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3005:3000
        volumes:
            - ./:/autohaus/
        command: "npm run dev"
networks:
    default:
        external: true
        name: "${DOCKER_NETWORK}"

