version: "3.9"
services:
    autohaus:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3005:3000
        volumes:
            - ./:/autohaus/
        command: "npm run start"
        deploy:
            resources:
                limits:
                    cpus: '1.25'
                    memory: 3000m
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
    postgresdockerautohaus:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: "${pguser}"
            POSTGRES_PASSWORD: "${pgpassword}"
        ports:
            - 5446:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data
        deploy:
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
    # adminer:
    #     image: adminer
    #     restart: always
    #     ports:
    #         - 8089:8080
volumes:
    postgres-data:
        driver: local
networks:
    default:
        external: true
        name: "${DOCKER_NETWORK}"
