version: "3.9"
services:
    autohaus:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3005:3000
        volumes:
            - ./:/autohaus/
        command: "npm run start"
        # deploy:
            # resources:
            #     limits:
            #         cpus: '1.25'
            #         memory: 3000m
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
                window: 120s
        driver: local
networks:
    default:
        external: true
        name: "${DOCKER_NETWORK}"
