version: "3.9"
services:
    autohaus:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3005:3000
        volumes:
            - ./:/autohaus/
        command: "npm run dev"
    postgresdockerautohaus:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: "${pguser}"
            POSTGRES_PASSWORD: "${pgpassword}"
        ports:
            - 5446:5432
        volumes:
            - postgres-data:/var/lib/postgresql/data
volumes:
    postgres-data:
        driver: local
networks:
    default:
        external: true
        name: "${DOCKER_NETWORK}"
# deploy:
#     resources:
#         cpus: '1.25'
#         memory: 3000m
