version: "3.9"
services:
    autohaus:
        env_file:
            - .env
        build:
            context: .
            dockerfile: Dockerfile.prod
            network: "${DOCKER_NETWORK}" 
        ports:
            - 3000:3000
        # volumes:
        #     - /efs:/app/
        command: "npm run server"
networks:
    default:
        external: true
        name: "${DOCKER_NETWORK}"

    